package cmd

import (
	"fmt"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/spf13/cobra"
)



var docsCmd = &cobra.Command{
	Use:   "docs [example-file]",
	Short: "Generate markdown documentation from your .env.example file",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		exampleFile := args[0]
		output, _ := cmd.Flags().GetString("output")

		vars, err := ParseEnvWithMetadata(exampleFile)
		if err != nil {
			fmt.Printf("Error reading %s: %v\n", exampleFile, err)
			os.Exit(1)
		}

		fmt.Printf("\nGenerating docs from %s...\n\n", exampleFile)

		md := buildMarkdown(vars, exampleFile)

		if output != "" {
			err := os.WriteFile(output, []byte(md), 0644)
			if err != nil {
				fmt.Printf("Error writing to %s: %v\n", output, err)
				os.Exit(1)
			}
			fmt.Printf("  Docs written to %s\n", output)
		} else {
			fmt.Println(md)
		}

		fmt.Printf("\n  %d variables documented.\n", len(vars))
	},
}



func buildMarkdown(vars []EnvVar, sourceFile string) string {
	var sb strings.Builder

	sb.WriteString("# Environment Variables\n\n")
	sb.WriteString(fmt.Sprintf("> Auto-generated by [Razify](https://github.com/Hossiy21/razify) from `%s`  \n", sourceFile))
	sb.WriteString(fmt.Sprintf("> Generated at: %s\n\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString("---\n\n")

	// Summary table
	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Variable | Required | Default | Description |\n")
	sb.WriteString("|----------|----------|---------|-------------|\n")

	for _, v := range vars {
		required := "No"
		if v.Required {
			required = "**Yes**"
		}
		defaultVal := v.Value
		if defaultVal == "" {
			defaultVal = "—"
		}
		comment := stripTags(v.Comment)
		if comment == "" {
			comment = "—"
		}
		sb.WriteString(fmt.Sprintf("| `%s` | %s | `%s` | %s |\n",
			v.Key, required, defaultVal, comment))
	}

	sb.WriteString("\n---\n\n")

	// Detailed section grouped by category
	currentCat := ""
	for _, v := range vars {
		if v.Category != currentCat {
			currentCat = v.Category
			if currentCat != "" {
				sb.WriteString(fmt.Sprintf("## %s\n\n", currentCat))
			} else {
				sb.WriteString("## Variables\n\n")
			}
		}

		sb.WriteString(fmt.Sprintf("### `%s`\n\n", v.Key))

		if v.Comment != "" {
			comment := stripTags(v.Comment)
			if comment != "" {
				sb.WriteString(fmt.Sprintf("%s\n\n", comment))
			}
		}

		if v.Required {
			sb.WriteString("- **Required:** Yes\n")
		} else {
			sb.WriteString("- **Required:** No\n")
		}

		if v.Value != "" {
			sb.WriteString(fmt.Sprintf("- **Default:** `%s`\n", v.Value))
		} else {
			sb.WriteString("- **Default:** None\n")
		}

		sb.WriteString("\n")
	}

	return sb.String()
}

func stripTags(comment string) string {
	tagRegex := regexp.MustCompile(`@\w+=[\w\-\.,]+`)
	return strings.TrimSpace(tagRegex.ReplaceAllString(comment, ""))
}

func init() {
	rootCmd.AddCommand(docsCmd)
	docsCmd.Flags().StringP("output", "o", "", "Write docs to a file instead of stdout")
}
