package cmd

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

type EnvVar struct {
	Key      string
	Value    string
	Comment  string
	Required bool
	Category string
}

var docsCmd = &cobra.Command{
	Use:   "docs [example-file]",
	Short: "Generate markdown documentation from your .env.example file",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		exampleFile := args[0]
		output, _ := cmd.Flags().GetString("output")

		vars, err := parseEnvFileWithComments(exampleFile)
		if err != nil {
			fmt.Printf("Error reading %s: %v\n", exampleFile, err)
			os.Exit(1)
		}

		fmt.Printf("\nGenerating docs from %s...\n\n", exampleFile)

		md := buildMarkdown(vars, exampleFile)

		if output != "" {
			err := os.WriteFile(output, []byte(md), 0644)
			if err != nil {
				fmt.Printf("Error writing to %s: %v\n", output, err)
				os.Exit(1)
			}
			fmt.Printf("  Docs written to %s\n", output)
		} else {
			fmt.Println(md)
		}

		fmt.Printf("\n  %d variables documented.\n", len(vars))
	},
}

func parseEnvFileWithComments(filename string) ([]EnvVar, error) {
	file, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	var vars []EnvVar
	var lastComment string
	var currentCategory string

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Empty line resets comment
		if line == "" {
			lastComment = ""
			continue
		}

		// Category header comment (## Category)
		if strings.HasPrefix(line, "##") {
			currentCategory = strings.TrimSpace(strings.TrimPrefix(line, "##"))
			lastComment = ""
			continue
		}

		// Regular comment
		if strings.HasPrefix(line, "#") {
			lastComment = strings.TrimSpace(strings.TrimPrefix(line, "#"))
			continue
		}

		// Key=Value line
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])

		vars = append(vars, EnvVar{
			Key:      key,
			Value:    value,
			Comment:  lastComment,
			Required: value == "" || strings.HasPrefix(value, "your-"),
			Category: currentCategory,
		})

		lastComment = ""
	}

	return vars, scanner.Err()
}

func buildMarkdown(vars []EnvVar, sourceFile string) string {
	var sb strings.Builder

	sb.WriteString("# Environment Variables\n\n")
	sb.WriteString(fmt.Sprintf("> Auto-generated by [Envy](https://github.com/hossiy21/envy) from `%s`  \n", sourceFile))
	sb.WriteString(fmt.Sprintf("> Generated at: %s\n\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString("---\n\n")

	// Summary table
	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Variable | Required | Default | Description |\n")
	sb.WriteString("|----------|----------|---------|-------------|\n")

	for _, v := range vars {
		required := "No"
		if v.Required {
			required = "**Yes**"
		}
		defaultVal := v.Value
		if defaultVal == "" {
			defaultVal = "—"
		}
		comment := v.Comment
		if comment == "" {
			comment = "—"
		}
		sb.WriteString(fmt.Sprintf("| `%s` | %s | `%s` | %s |\n",
			v.Key, required, defaultVal, comment))
	}

	sb.WriteString("\n---\n\n")

	// Detailed section grouped by category
	currentCat := ""
	for _, v := range vars {
		if v.Category != currentCat {
			currentCat = v.Category
			if currentCat != "" {
				sb.WriteString(fmt.Sprintf("## %s\n\n", currentCat))
			} else {
				sb.WriteString("## Variables\n\n")
			}
		}

		sb.WriteString(fmt.Sprintf("### `%s`\n\n", v.Key))

		if v.Comment != "" {
			sb.WriteString(fmt.Sprintf("%s\n\n", v.Comment))
		}

		if v.Required {
			sb.WriteString("- **Required:** Yes\n")
		} else {
			sb.WriteString("- **Required:** No\n")
		}

		if v.Value != "" {
			sb.WriteString(fmt.Sprintf("- **Default:** `%s`\n", v.Value))
		} else {
			sb.WriteString("- **Default:** None\n")
		}

		sb.WriteString("\n")
	}

	return sb.String()
}

func init() {
	rootCmd.AddCommand(docsCmd)
	docsCmd.Flags().StringP("output", "o", "", "Write docs to a file instead of stdout")
}
